namespace mClient.Constants
{
    public static class SpellAuras
    {
        public const int GHOST_1 = 8326;
        public const int GHOST_2 = 9036;
        public const int GHOST_WISP = 20584;
    }

    public static class SkillConstants
    {
        public const int MAX_SKILL_TYPE = 763;
    }

    public enum SpellSchools
    {
        SPELL_SCHOOL_NORMAL = 0,                //< Physical, Armor
        SPELL_SCHOOL_HOLY = 1,
        SPELL_SCHOOL_FIRE = 2,
        SPELL_SCHOOL_NATURE = 3,
        SPELL_SCHOOL_FROST = 4,
        SPELL_SCHOOL_SHADOW = 5,
        SPELL_SCHOOL_ARCANE = 6
    };


    // Data from SpellLine.dbc (1.12.1 checked)
    public enum SkillType
    {
        SKILL_NONE = 0,

        SKILL_FROST = 6,
        SKILL_FIRE = 8,
        SKILL_ARMS = 26,
        SKILL_COMBAT = 38,
        SKILL_SUBTLETY = 39,
        SKILL_POISONS = 40,
        SKILL_SWORDS = 43,
        SKILL_AXES = 44,
        SKILL_BOWS = 45,
        SKILL_GUNS = 46,
        SKILL_BEAST_MASTERY = 50,
        SKILL_SURVIVAL = 51,
        SKILL_MACES = 54,
        SKILL_2H_SWORDS = 55,
        SKILL_HOLY = 56,
        SKILL_SHADOW = 78,
        SKILL_DEFENSE = 95,
        SKILL_LANG_COMMON = 98,
        SKILL_RACIAL_DWARVEN = 101,
        SKILL_LANG_ORCISH = 109,
        SKILL_LANG_DWARVEN = 111,
        SKILL_LANG_DARNASSIAN = 113,
        SKILL_LANG_TAURAHE = 115,
        SKILL_DUAL_WIELD = 118,
        SKILL_RACIAL_TAUREN = 124,
        SKILL_ORC_RACIAL = 125,
        SKILL_RACIAL_NIGHT_ELF = 126,
        SKILL_FIRST_AID = 129,
        SKILL_FERAL_COMBAT = 134,
        SKILL_STAVES = 136,
        SKILL_LANG_THALASSIAN = 137,
        SKILL_LANG_DRACONIC = 138,
        SKILL_LANG_DEMON_TONGUE = 139,
        SKILL_LANG_TITAN = 140,
        SKILL_LANG_OLD_TONGUE = 141,
        SKILL_SURVIVAL2 = 142,
        SKILL_RIDING_HORSE = 148,
        SKILL_RIDING_WOLF = 149,
        SKILL_RIDING_TIGER = 150,
        SKILL_RIDING_RAM = 152,
        SKILL_SWIMING = 155,
        SKILL_2H_MACES = 160,
        SKILL_UNARMED = 162,
        SKILL_MARKSMANSHIP = 163,
        SKILL_BLACKSMITHING = 164,
        SKILL_LEATHERWORKING = 165,
        SKILL_ALCHEMY = 171,
        SKILL_2H_AXES = 172,
        SKILL_DAGGERS = 173,
        SKILL_THROWN = 176,
        SKILL_HERBALISM = 182,
        SKILL_GENERIC_DND = 183,
        SKILL_RETRIBUTION = 184,
        SKILL_COOKING = 185,
        SKILL_MINING = 186,
        SKILL_PET_IMP = 188,
        SKILL_PET_FELHUNTER = 189,
        SKILL_TAILORING = 197,
        SKILL_ENGINEERING = 202,
        SKILL_PET_SPIDER = 203,
        SKILL_PET_VOIDWALKER = 204,
        SKILL_PET_SUCCUBUS = 205,
        SKILL_PET_INFERNAL = 206,
        SKILL_PET_DOOMGUARD = 207,
        SKILL_PET_WOLF = 208,
        SKILL_PET_CAT = 209,
        SKILL_PET_BEAR = 210,
        SKILL_PET_BOAR = 211,
        SKILL_PET_CROCILISK = 212,
        SKILL_PET_CARRION_BIRD = 213,
        SKILL_PET_CRAB = 214,
        SKILL_PET_GORILLA = 215,
        SKILL_PET_RAPTOR = 217,
        SKILL_PET_TALLSTRIDER = 218,
        SKILL_RACIAL_UNDED = 220,
        SKILL_CROSSBOWS = 226,
        SKILL_WANDS = 228,
        SKILL_POLEARMS = 229,
        SKILL_PET_SCORPID = 236,
        SKILL_ARCANE = 237,
        SKILL_PET_TURTLE = 251,
        SKILL_ASSASSINATION = 253,
        SKILL_FURY = 256,
        SKILL_PROTECTION = 257,
        SKILL_BEAST_TRAINING = 261,
        SKILL_PROTECTION2 = 267,
        SKILL_PET_TALENTS = 270,
        SKILL_PLATE_MAIL = 293,
        SKILL_LANG_GNOMISH = 313,
        SKILL_LANG_TROLL = 315,
        SKILL_ENCHANTING = 333,
        SKILL_DEMONOLOGY = 354,
        SKILL_AFFLICTION = 355,
        SKILL_FISHING = 356,
        SKILL_ENHANCEMENT = 373,
        SKILL_RESTORATION = 374,
        SKILL_ELEMENTAL_COMBAT = 375,
        SKILL_SKINNING = 393,
        SKILL_MAIL = 413,
        SKILL_LEATHER = 414,
        SKILL_CLOTH = 415,
        SKILL_SHIELD = 433,
        SKILL_FIST_WEAPONS = 473,
        SKILL_RIDING_RAPTOR = 533,
        SKILL_RIDING_MECHANOSTRIDER = 553,
        SKILL_RIDING_UNDEAD_HORSE = 554,
        SKILL_RESTORATION2 = 573,
        SKILL_BALANCE = 574,
        SKILL_DESTRUCTION = 593,
        SKILL_HOLY2 = 594,
        SKILL_DISCIPLINE = 613,
        SKILL_LOCKPICKING = 633,
        SKILL_PET_BAT = 653,
        SKILL_PET_HYENA = 654,
        SKILL_PET_OWL = 655,
        SKILL_PET_WIND_SERPENT = 656,
        SKILL_LANG_GUTTERSPEAK = 673,
        SKILL_RIDING_KODO = 713,
        SKILL_RACIAL_TROLL = 733,
        SKILL_RACIAL_GNOME = 753,
        SKILL_RACIAL_HUMAN = 754,
        SKILL_PET_EVENT_RC = 758,
        SKILL_RIDING = 762,
    }
}
